### ISSUE TITLE
session_id not generated

### ISSUE THREAD

**Issue by jacktheboss220** [Gimenz/insta-fetcher#16]
tried many times
error - throw new Error('Username or password is incorrect. Please check and try again');
^

Error: Username or password is incorrect. Please check and try again
at d:\Github\MyBitBot-MD\node_modules\insta-fetcher\dist\helper\Session.js:76:19
at Generator.next ()
at fulfilled (d:\Github\MyBitBot-MD\node_modules\insta-fetcher\dist\helper\Session.js:5:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

with same username and password i'm able to login in chrome.
help

**Comment by jacktheboss220** [comment]
tried many times
error - throw new Error('Username or password is incorrect. Please check and try again');
                  ^

Error: Username or password is incorrect. Please check and try again
    at d:\Github\MyBitBot-MD\node_modules\insta-fetcher\dist\helper\Session.js:76:19
    at Generator.next (<anonymous>)
    at fulfilled (d:\Github\MyBitBot-MD\node_modules\insta-fetcher\dist\helper\Session.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

with same username and password i'm able to login in chrome.
help

**Comment by Gimenz** [comment]
hmmm, even if the username and password are correct, it should be possible. i think you has changed your password maybe
