### ISSUE TITLE
[ BUG ] CANNOT READ PROPERTIES

### ISSUE THREAD

**Issue by bolaxd** [Gimenz/insta-fetcher#25]
const item = metadata.items[0];
                                       ^
TypeError: Cannot read properties of undefined (reading '0')
    at igApi.<anonymous> (/data/data/com.termux/files/home/scraper-ig/node_modules/insta-fetcher/dist/index.js:178:40)
    at Generator.next (<anonymous>)
    at fulfilled (/data/data/com.termux/files/home/scraper-ig/node_modules/insta-fetcher/dist/index.js:35:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Gimenz** [comment]
udah setting cookie belum?

**Comment by bolaxd** [comment]
Sudah pak

**Comment by bolaxd** [comment]
Nampak nya yg bisa V2 dan 1 ngga bisa

**Comment by thoriqazzikraa** [comment]
> const item = metadata.items[0]; ^ TypeError: Cannot read properties of undefined (reading '0') at igApi. (/data/data/com.termux/files/home/scraper-ig/node_modules/insta-fetcher/dist/index.js:178:40) at Generator.next () at fulfilled (/data/data/com.termux/files/home/scraper-ig/node_modules/insta-fetcher/dist/index.js:35:58) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

emg biasanya ada vid yg gabisa didownload
kasi try { } catch aja
gw kasi manual return errornya

**Comment by bolaxd** [comment]
Tetapi setelah saya fork dan saya recode sedikit terlihst normsl lagi 🥇 hihihi, jadi mungkin terdapat kesalahan saat return maybe

**Comment by Gimenz** [comment]
mantap, bisa di pull request kalo aman.

**Comment by adarsh-chakraborty** [comment]
Same problem when fetching reels or a post /p/postid

**Comment by jigneshk5** [comment]
> Same problem when fetching reels or a post /p/postid

Hi @adarsh-chakraborty , Are you able to use await getCookie("username","password");  

I'm getting challenge_required error. Please help me fix the issue
