### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by 89z** [Gimenz/insta-fetcher#4]
Using this code:

~~~js
let { igApi } = require('insta-fetcher');
let ig = new igApi();

ig.fetchPost('https://www.instagram.com/reel/CXhW_4sp32Z/').then((res) => {
	console.log(res);
});
~~~

I get this result:

~~~
D:\Desktop\etc\node_modules\insta-fetcher\dist\index.js:225
            const item = metadata.items[0];
                                       ^

TypeError: Cannot read properties of undefined (reading '0')
    at igApi.<anonymous> (D:\Desktop\etc\node_modules\insta-fetcher\dist\index.js:225:40)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Desktop\etc\node_modules\insta-fetcher\dist\index.js:19:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
~~~

**Comment by Gimenz** [comment]
i think you didn't put session id? have you read REAADME.md ?

**Comment by 89z** [comment]
Is it possible to have anonymous access?

**Comment by Gimenz** [comment]
what do you mean?
